DNB/DNB/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('public.urls')),
    path('',include('Exam.urls')),
]

DNB/Exam/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
path('Room',views.addroom),
path('Room_view',views.roomviews),
path('Add_exam',views.add_exam),
path('Exam_view',views.examview),
path('Classallocation',views.classaloc),
path('Classallocation_view',views.classview),


]

DNB/Exam/models.py
from django.db import models
from django.db import models
from public.models import *


# Create your models here.



class room(models.Model):
    roomname=models.CharField(max_length=500,default='')
    row=models.IntegerField(null=True)
    column=models.IntegerField(null=True)
    strength=models.IntegerField(null=True)



class exam(models.Model):
    department = models.ForeignKey(Departments,on_delete=models.CASCADE,null=True)
    semester = models.ForeignKey(Semesters,on_delete=models.CASCADE,null=True)
    subname = models.ForeignKey(Subjects,on_delete=models.CASCADE,null=True)
    examname=models.CharField(max_length=500,default='')
    date=models.DateField(max_length=500,default='')
    starttime=models.TimeField(max_length=500,default='')
    endtime=models.TimeField(max_length=500,default='')


class Class(models.Model):
    examname=models.TimeField(max_length=500,default='')
    roomname=models.TimeField(max_length=500,default='')
   

DNB/Exam/forms.py
from django import forms
from .models import *



class roomaddingform(forms.ModelForm):
    class Meta:
        model=room
        fields=['roomname','row','column']
        widgets={
            "roomname":forms.TextInput(attrs={'class':'form-input','style':'width : 90%;'}),
            "row":forms.TextInput(attrs={'class':'form-input','style':'width : 90%;'}),
            "column":forms.TextInput(attrs={'class':'form-input','style':'width : 90%;'}),
        }

class examform(forms.ModelForm):
    # departmentname = forms.ModelChoiceField(queryset=Departments.objects.all())
    # semestername = forms.ModelChoiceField(queryset=Semesters.objects.all())

    class Meta:
        model = exam
        fields = ['examname','date','starttime','endtime']
        widgets = {
            
            "examname": forms.TextInput(attrs={'class': 'form-input', 'style': 'width : 90%;'}),
            "date": forms.TextInput(attrs={'class': 'form-input', 'style': 'width : 90%;'}),
            "starttime": forms.TextInput(attrs={'class': 'form-input', 'style': 'width : 90%;'}),
            "endtime": forms.TextInput(attrs={'class': 'form-input', 'style': 'width : 90%;'}),
        }

    # def __init__(self, *args, **kwargs):
    #     super(examform, self).__init__(*args, **kwargs)
    #     self.fields['semestername'].widget.attrs.update({'data-did': ''})


class classalocform(forms.ModelForm):
    class Meta:
        model = Class
        fields = ['roomname','examname']
        widgets = {
            "roomname": forms.TextInput(attrs={'class': 'form-input', 'style': 'width : 90%;'}),
            "examname": forms.TextInput(attrs={'class': 'form-input', 'style': 'width : 90%;'}),

            
           
        }

DNB/Exam/views.py
from django.shortcuts import render
from .forms import *
from django.shortcuts import render,redirect
from public.models import *


# Create your views here.


def addroom(request):
    form = roomaddingform(request.POST,request.FILES)
    if request.method=="POST":  
        if form.is_valid():
            row=form.cleaned_data['row']
            column=form.cleaned_data['column']
            strength=row*column
            room.objects.create(
                roomname=form.cleaned_data['roomname'],
                row=row,
                column=column,
                strength=strength
             )
            return redirect('/Room')

    else:
        form = roomaddingform()
        return render(request,'Room.html',{'form':form})


def roomviews(request):
    rooms=room.objects.all()
    # print(rooms)
    return render(request,'Room_view.html',{'rooms':rooms})    


def add_exam(request):
    form = examform(request.POST,request.FILES)
    dep = Departments.objects.all()
    sem = Semesters.objects.all()
    sub = Subjects.objects.all()
    if request.method=="POST":
            exam.objects.create(
                department=Departments.objects.get(id=request.POST['depname']),
                subname=Subjects.objects.get(id=request.POST['subname']),
                semester=Semesters.objects.get(id=request.POST['semname']),
                examname=request.POST['examname'],
                date=request.POST['date'],
                starttime=request.POST['starttime'],
                endtime=request.POST['endtime'],
            )

            return redirect('/Add_exam')
      
    else:
        form = examform()
        dep=Departments.objects.all()
        sem=Semesters.objects.all()
        sub=Subjects.objects.all()

        return render(request,'Add_exam.html',{'form':form,'dep':dep ,'sem':sem ,'sub':sub})


def examview(request):
    exams=exam.objects.all()
    # print(rooms)
    return render(request,'Exam_view.html',{'exams':exams}) 


def classaloc(request):
    form = classalocform(request.POST,request.FILES)
    if request.method=="POST":  
        if form.is_valid():
            Class.objects.create(
                examname=exam.objects.get(id=request.POST['examname']),
                roomname=room.objects.get(id=request.POST['roomname']),




            )
                
            return redirect('/Classallocation')

    else: 
        form = classalocform()

        return render(request,'Classallocation.html',{'form':form})

def classview(request):
    classview=Class.objects.all()
    # print(rooms)
    return render(request,'Classallocation_view.html',{'classview':classview})     

DNB/Exam/templates/Add_exam.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<form action="/Add_exam" method="post">
    <div class="mb-3">
        <select class="form-select form-select-xl mb-3" aria-label=".form-select-xl example" class="form-control" name="depname" id="id_department">
        <option selected>-----Select Department-----</option>
        {% for i in dep%}
        <option value="{{i.id}}">{{i.departmentname}}</option>
        {% endfor %}
      </select>
    </div>
      
    <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="semname" id="id_semester">
                <option selected>---- Select Semester------</option>
        {% for i in sem%}
        <option value="{{i.id}}" data-did="{{i.department.id}}">{{i.semestername}}</option>
        {% endfor %}
    
        <!-- <input type="submit"> -->
        {% csrf_token %}
        
    </select>
    <div class="mb-3">
        <select class="form-select form-select-xl mb-3" aria-label=".form-select-xl example" class="form-control" name="subname" id="id_subject">
        <option selected>-----Select Subject-----</option>
        {% for i in sub%}
        <option value="{{i.id}}" data-sem="{{i.semester.id}}">{{i.subname}}</option>
        {% endfor %}
      </select>
      <h1>fgcngfgfghfh</h1>

    <div class="form-group">
        <label for="name" class="form-label" style="color: red;">Examname:</label>
        <input type="text" name="examname" id="" class="form-input" style="width: 100%;" value="">
    </div>
    
    <div class="form-group">
        <label for="" class="form-label">Date:</label>
        <input type="date" name="date" id="" class="form-input" style="width: 100%;" value="">
    </div>  

    <div class="form-group">
        <label for="" class="form-label">Start time:</label>
        <input type="time" name="starttime" id="" class="form-input" style="width: 100%;" value="">
    </div> 

    <div class="form-group">
        <label for="" class="form-label">End time:</label>
        <input type="time" name="endtime" id="" class="form-input" style="width: 100%;" value="">
    </div> 
  

    <input type="submit">
</form>
   

<script>
    $("#id_department").change(function(){
    //   $("#id_semester").val('');
      $("#id_semester").children('option').hide();
      var id_department=$(this).val();
      $("#id_semester").children("option[data-did="+id_department+"]").show();
        
    })

    $(document).ready(function(){
        $("#id_semester").change(function(){
            var selectedDepartment = $(this).val();
            // $("#id_subject").val('');
            $("#id_subject").children('option').hide();
            $("#id_subject").children("option[data-sem=" + selectedDepartment +"]").show();
            // $("#id_semestername option[data-did='" + selectedDepartment + "']").show();
        });
    });
</script>
{%endblock%}

DNB/Exam/templates/Classallocation.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}

<form action="/Classallocation" method="post">
    <div class="mb-3">
        <select class="form-select form-select-xl mb-3" aria-label=".form-select-xl example" class="form-control" name="depname" id="id_department">
        <option selected>-----Exam-----</option>
        {% for i in exams%}
        <option value="{{i.id}}">{{i.examname}}</option>
        {% endfor %}
      </select>
    </div>
    {% csrf_token %}


    <div class="mb-3">
        <select class="form-select form-select-xl mb-3" aria-label=".form-select-xl example" class="form-control" name="depname" id="id_department">
        <option selected>-----Select Class-----</option>
        {% for i in room%}
        <option value="{{i.id}}">{{i.roomname}}</option>
        {% endfor %}
      </select>
    </div>

    <div class="mb-3">
      <select class="form-select form-select-xl mb-3" aria-label=".form-select-xl example" class="form-control" name="depname" id="id_department">
      <option selected>-----Select Staff-----</option>
      {% for i in staffform %}
      <option value="{{i.id}}">{{i.username}}</option>
      {% endfor %}
    </select>
  </div>
    <input type="submit">
    <!-- {{ form.as_p }} -->




{%endblock%}

DNB/Exam/templates/Classallocation_view.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}


<table class="table">
    <thead>
      <tr>
        <th scope="col">Examname</th>
      
        <th scope="col"> Roomname</th>
        <th scope="col">Staff</th>


        <!-- <th scope="col">Date_of_birth</th>
        <th scope="col">Experience</th>
        <th scope="col">Qualification</th>
        <th scope="col">Department</th> -->
      </tr>
    </thead>
    <tbody>
      {% for i in sub %}
      <tr>
        <td>{{i.subname}}</td>
        <!-- <td>{{i.description}}</td> -->
        <td>{{i.department.departmentname}}</td>
        <td>{{i.semester.semestername}}</td>
        <!-- <td>{{i.date_of_birth}}</td>
        <td>{{i.experience}}</td>
        <td>{{i.qualification}}</td>
        <td>{{i.department}}</td> -->
      </tr>
      {% endfor %}
    </tbody>
  </table>
{%endblock%}

DNB/Exam/templates/Exam_view.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}


<table class="table">
    <thead>
      <tr>
        <th scope="col">Department</th>
        <th scope="col">Semester</th>
        <th scope="col">Subjuct</th>
        <th scope="col">Exam name</th>
        <th scope="col">Date </th>
        <th scope="col">Endtime</th>
        <th scope="col">Starttime</th>
        <!-- <th scope="col">endtime</th> -->
      </tr>
    </thead>
    <tbody>
      {% for i in exams %}
      <tr>
        <td>{{i.department.departmentname}}</td>
        <td>{{i.semester.semestername}}</td>
        <td>{{i.subname.subname}}</td>
        <td>{{i.examname}}</td>
        <td>{{i.date}}</td>
        <td>{{i.starttime}}</td>
        <td>{{i.endtime}}</td>
        <!-- <td>{{i.department}}</td> -->
      </tr>
      {% endfor %}
    </tbody>
  </table>
{%endblock%}

DNB/Exam/templates/Room.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}



<form action="/Room" method="post">
    <!-- <section class="w3l-skill-breadcrum">
        <div class="breadcrum">
          
        </div>
      </section>
     
      <section class="w3l-contacts-12" id="contact">
        <div class="container py-5">
          <div class="contacts12-main py-md-3">
            <div class="header-section text-center">
              <h3 class="mb-md-5 mb-4">Add department</h3> -->
    {% csrf_token %}
     {{form.as_p}} 
    <!-- <label for="Department">Department Name</label>
    <input type="text" id="sum"><br>
    <label for="Discription">Discription</label>
    <input type="textarea" id="sums"><br>
     -->
    <input type="submit">
</form>
{%endblock%}

DNB/Exam/templates/Room_view.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}


<table class="table">
    <thead>
      <tr>
        <th scope="col">roomname</th>
        <th scope="col">row</th>
        <th scope="col">column</th>
        <th scope="col">strength</th>
        <!-- <th scope="col">Date_of_birth</th>
        <th scope="col">Experience</th>
        <th scope="col">Qualification</th>
        <th scope="col">Department</th> -->
      </tr>
    </thead>
    <tbody>
      {% for i in rooms %}
      <tr>
        <td>{{i.roomname}}</td>
        <td>{{i.row}}</td>
        <td>{{i.column}}</td>
        <td>{{i.strength}}</td>
        <!-- <td>{{i.date_of_birth}}</td>
        <td>{{i.experience}}</td>
        <td>{{i.qualification}}</td>
        <td>{{i.department}}</td> -->
      </tr>
      {% endfor %}
    </tbody>
  </table>
{%endblock%}